/*
 * SweetPotato Server API
 *
 * Sonolusの基本APIを拡張する感じ。 ユーザー認証はFirebaseAuthorizationを通してやる。
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	gen "github.com/PurplePalette/sonolus-uploader-core/gen"
)

func main() {
	log.Printf("Server started")

	BackgroundsApiService := gen.NewBackgroundsApiService()
	BackgroundsApiController := gen.NewBackgroundsApiController(BackgroundsApiService)

	EffectsApiService := gen.NewEffectsApiService()
	EffectsApiController := gen.NewEffectsApiController(EffectsApiService)

	EnginesApiService := gen.NewEnginesApiService()
	EnginesApiController := gen.NewEnginesApiController(EnginesApiService)

	InfoApiService := gen.NewInfoApiService()
	InfoApiController := gen.NewInfoApiController(InfoApiService)

	LevelsApiService := gen.NewLevelsApiService()
	LevelsApiController := gen.NewLevelsApiController(LevelsApiService)

	ParticlesApiService := gen.NewParticlesApiService()
	ParticlesApiController := gen.NewParticlesApiController(ParticlesApiService)

	SkinsApiService := gen.NewSkinsApiService()
	SkinsApiController := gen.NewSkinsApiController(SkinsApiService)

	TestsApiService := gen.NewTestsApiService()
	TestsApiController := gen.NewTestsApiController(TestsApiService)

	UsersApiService := gen.NewUsersApiService()
	UsersApiController := gen.NewUsersApiController(UsersApiService)

	router := gen.NewRouter(BackgroundsApiController, EffectsApiController, EnginesApiController, InfoApiController, LevelsApiController, ParticlesApiController, SkinsApiController, TestsApiController, UsersApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
