/*
 * SweetPotato Server API
 *
 * Sonolusの基本APIを拡張する感じ。 ユーザー認証はFirebaseAuthorizationを通してやる。
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package potato

import (
	"context"
	"encoding/json"
	"log"
	"net/http"

	"cloud.google.com/go/firestore"
	"github.com/PurplePalette/sonolus-uploader-core/utils/request"
)

// TestsApiService is a service that implents the logic for the TestsApiServicer
// This service should implement the business logic for every endpoint for the TestsApi API.
// Include any external packages or services that will be required by this service.
type TestsApiService struct {
	firestore *firestore.Client
	cache     *CacheService
}

// NewTestsApiService creates a default api service
func NewTestsApiService(firestore *firestore.Client, cache *CacheService) TestsApiServicer {
	return &TestsApiService{firestore: firestore, cache: cache}
}

// GetTestServerInfo - Get user server info
func (s *TestsApiService) GetTestServerInfo(ctx context.Context, testId string) (ImplResponse, error) {
	if _, err := s.cache.GetUserIdFromTest(testId); err != nil {
		return Response(http.StatusNotFound, nil), nil
	}
	welcome, err := s.cache.news.Get("sweetPotatoTestWelcome")
	parsedNews := welcome.(News)
	if err != nil {
		log.Print(err)
		return Response(http.StatusInternalServerError, nil), nil
	}
	parsedNews.Level.Artists = testId
	welcome2, err := s.cache.news.Get("sweetPotatoTestWelcome2")
	parsedNews2 := welcome2.(News)
	if err != nil {
		log.Print(err)
		return Response(http.StatusInternalServerError, nil), nil
	}
	resp := ServerInfo{
		Levels:      []Level{parsedNews.Level, parsedNews2.Level},
		Skins:       []Skin{},
		Backgrounds: []Background{},
		Effects:     []Effect{},
		Particles:   []Particle{},
		Engines:     []Engine{},
	}
	return Response(200, resp), nil
}

// GetTestsBackgrounds - Get backgrounds for test
func (s *TestsApiService) GetTestsBackgrounds(ctx context.Context, testId string, localization string, page int32, keywords string) (ImplResponse, error) {
	userId, err := s.cache.GetUserIdFromTest(testId)
	if err != nil {
		return Response(http.StatusNotFound, nil), nil
	}
	query := request.ParseSearchQuery(keywords)
	query.Filter.UserId = userId
	query.Filter.Public = false
	pages := s.cache.backgrounds.Pages()
	items, err := s.cache.backgrounds.GetPage(page, query)
	if err != nil {
		log.Fatal(err)
		return Response(500, nil), nil
	}
	var backgrounds []Background
	if err := json.Unmarshal(items, &backgrounds); err != nil {
		return Response(500, nil), nil
	}
	resp := GetBackgroundListResponse{
		PageCount: pages,
		Items:     backgrounds,
	}
	return Response(200, resp), nil
}

// GetTestsEffects - Get effects for test
func (s *TestsApiService) GetTestsEffects(ctx context.Context, testId string, localization string, page int32, keywords string) (ImplResponse, error) {
	userId, err := s.cache.GetUserIdFromTest(testId)
	if err != nil {
		return Response(http.StatusNotFound, nil), nil
	}
	query := request.ParseSearchQuery(keywords)
	query.Filter.UserId = userId
	query.Filter.Public = false
	pages := s.cache.effects.Pages()
	items, err := s.cache.effects.GetPage(page, query)
	if err != nil {
		log.Fatal(err)
		return Response(500, nil), nil
	}
	var effects []Effect
	if err := json.Unmarshal(items, &effects); err != nil {
		return Response(500, nil), nil
	}
	resp := GetEffectListResponse{
		PageCount: pages,
		Items:     effects,
	}
	return Response(200, resp), nil
}

// GetTestsEngines - Get engines for test
func (s *TestsApiService) GetTestsEngines(ctx context.Context, testId string, localization string, page int32, keywords string) (ImplResponse, error) {
	userId, err := s.cache.GetUserIdFromTest(testId)
	if err != nil {
		return Response(http.StatusNotFound, nil), nil
	}
	query := request.ParseSearchQuery(keywords)
	query.Filter.UserId = userId
	query.Filter.Public = false
	pages := s.cache.engines.Pages()
	items, err := s.cache.engines.GetPage(page, query)
	if err != nil {
		log.Fatal(err)
		return Response(500, nil), nil
	}
	var engines []Engine
	if err := json.Unmarshal(items, &engines); err != nil {
		return Response(500, nil), nil
	}
	resp := GetEngineListResponse{
		PageCount: pages,
		Items:     engines,
	}
	return Response(200, resp), nil
}

// GetTestsLevels - Get levels for test
func (s *TestsApiService) GetTestsLevels(ctx context.Context, testId string, localization string, page int32, keywords string) (ImplResponse, error) {
	userId, err := s.cache.GetUserIdFromTest(testId)
	if err != nil {
		return Response(http.StatusNotFound, nil), nil
	}
	query := request.ParseSearchQuery(keywords)
	query.Filter.UserId = userId
	query.Filter.Public = false
	pages := s.cache.levels.Pages()
	items, err := s.cache.levels.GetPage(page, query)
	if err != nil {
		log.Fatal(err)
		return Response(500, nil), nil
	}
	var levels []Level
	if err := json.Unmarshal(items, &levels); err != nil {
		return Response(500, nil), nil
	}
	resp := GetLevelListResponse{
		PageCount: pages,
		Items:     levels,
	}
	return Response(200, resp), nil
}

// GetTestsParticles - Get particles for test
func (s *TestsApiService) GetTestsParticles(ctx context.Context, testId string, localization string, page int32, keywords string) (ImplResponse, error) {
	userId, err := s.cache.GetUserIdFromTest(testId)
	if err != nil {
		return Response(http.StatusNotFound, nil), nil
	}
	query := request.ParseSearchQuery(keywords)
	query.Filter.UserId = userId
	query.Filter.Public = false
	pages := s.cache.particles.Pages()
	items, err := s.cache.particles.GetPage(page, query)
	if err != nil {
		log.Fatal(err)
		return Response(500, nil), nil
	}
	var particles []Particle
	if err := json.Unmarshal(items, &particles); err != nil {
		return Response(500, nil), nil
	}
	resp := GetParticleListResponse{
		PageCount: pages,
		Items:     particles,
	}
	return Response(200, resp), nil
}

// GetTestsSkins - Get skins for test
func (s *TestsApiService) GetTestsSkins(ctx context.Context, testId string, localization string, page int32, keywords string) (ImplResponse, error) {
	userId, err := s.cache.GetUserIdFromTest(testId)
	if err != nil {
		return Response(http.StatusNotFound, nil), nil
	}
	query := request.ParseSearchQuery(keywords)
	query.Filter.UserId = userId
	query.Filter.Public = false
	pages := s.cache.skins.Pages()
	items, err := s.cache.skins.GetPage(page, query)
	if err != nil {
		log.Fatal(err)
		return Response(500, nil), nil
	}
	var skins []Skin
	if err := json.Unmarshal(items, &skins); err != nil {
		return Response(500, nil), nil
	}
	resp := GetSkinListResponse{
		PageCount: pages,
		Items:     skins,
	}
	return Response(200, resp), nil
}
