/*
 * SweetPotato Server API
 *
 * Sonolusの基本APIを拡張する感じ。 ユーザー認証はFirebaseAuthorizationを通してやる。
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package potato

import (
	"context"
	"errors"
	"log"
	"net/http"

	"cloud.google.com/go/firestore"
	"github.com/PurplePalette/sonolus-uploader-core/utils/request"
)

// BackgroundsApiService is a service that implents the logic for the BackgroundsApiServicer
// This service should implement the business logic for every endpoint for the BackgroundsApi API.
// Include any external packages or services that will be required by this service.
type BackgroundsApiService struct {
	firestore *firestore.Client
	cache     *CacheService
}

// NewBackgroundsApiService creates a default api service
func NewBackgroundsApiService(firestore *firestore.Client, cache *CacheService) BackgroundsApiServicer {
	return &BackgroundsApiService{firestore: firestore, cache: cache}
}

// AddBackground - Add background
func (s *BackgroundsApiService) AddBackground(ctx context.Context, backgroundName string, background Background) (ImplResponse, error) {
	// This endpoint is not working without authorization
	if !request.IsLoggedIn(ctx) {
		return Response(http.StatusUnauthorized, nil), nil
	}
	// Check the background name is not already used
	col := s.firestore.Collection("backgrounds")
	if _, err := col.Doc(backgroundName).Get(ctx); err == nil {
		return Response(http.StatusConflict, nil), nil
	}
	// Inject userId to background
	userId, err := request.GetUserId(ctx)
	if err != nil {
		log.Fatalln("Error getting userId:", err)
		return Response(500, nil), nil
	}
	background.UserId = userId
	// Add background to firebase
	_, err = col.Doc(backgroundName).Set(ctx, background)
	if err != nil {
		log.Fatalln("Error posting background:", err)
		return Response(500, nil), nil
	}
	return Response(200, nil), nil
}

// EditBackground - Edit background
func (s *BackgroundsApiService) EditBackground(ctx context.Context, backgroundName string, background Background) (ImplResponse, error) {
	if !request.IsLoggedIn(ctx) {
		return Response(http.StatusUnauthorized, nil), nil
	}

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	//TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	//return Response(400, nil),nil

	//TODO: Uncomment the next line to return response Response(403, {}) or use other options such as http.Ok ...
	//return Response(403, nil),nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("EditBackground method not implemented")
}

// GetBackground - Get background
func (s *BackgroundsApiService) GetBackground(ctx context.Context, backgroundName string) (ImplResponse, error) {
	// TODO - update GetBackground with the required logic for this service method.
	// Add api_backgrounds_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, GetBackgroundResponse{}) or use other options such as http.Ok ...
	//return Response(200, GetBackgroundResponse{}), nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetBackground method not implemented")
}

// GetBackgroundList - Get background list
func (s *BackgroundsApiService) GetBackgroundList(ctx context.Context, localization string, page int32, keywords string) (ImplResponse, error) {
	// TODO - update GetBackgroundList with the required logic for this service method.
	// Add api_backgrounds_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, GetBackgroundListResponse{}) or use other options such as http.Ok ...
	//return Response(200, GetBackgroundListResponse{}), nil

	_ = request.ParseSearchQuery(keywords)
	return Response(http.StatusNotImplemented, nil), errors.New("GetBackgroundList method not implemented")
}
