/*
 * SweetPotato Server API
 *
 * Sonolusの基本APIを拡張する感じ。 ユーザー認証はFirebaseAuthorizationを通してやる。
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package potato

import (
	"context"
	"errors"
	"net/http"

	"firebase.google.com/go/db"
)

// EffectsApiService is a service that implents the logic for the EffectsApiServicer
// This service should implement the business logic for every endpoint for the EffectsApi API.
// Include any external packages or services that will be required by this service.
type EffectsApiService struct {
	db *db.Client
}

// NewEffectsApiService creates a default api service
func NewEffectsApiService(db *db.Client) EffectsApiServicer {
	return &EffectsApiService{db: db}
}

// AddEffect - Add effect
func (s *EffectsApiService) AddEffect(ctx context.Context, effectName string, effect Effect) (ImplResponse, error) {
	// TODO - update AddEffect with the required logic for this service method.
	// Add api_effects_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	//TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	//return Response(400, nil),nil

	//TODO: Uncomment the next line to return response Response(401, {}) or use other options such as http.Ok ...
	//return Response(401, nil),nil

	//TODO: Uncomment the next line to return response Response(409, {}) or use other options such as http.Ok ...
	//return Response(409, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("AddEffect method not implemented")
}

// EditEffect - Edit effect
func (s *EffectsApiService) EditEffect(ctx context.Context, effectName string, effect Effect) (ImplResponse, error) {
	// TODO - update EditEffect with the required logic for this service method.
	// Add api_effects_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	//TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	//return Response(400, nil),nil

	//TODO: Uncomment the next line to return response Response(401, {}) or use other options such as http.Ok ...
	//return Response(401, nil),nil

	//TODO: Uncomment the next line to return response Response(403, {}) or use other options such as http.Ok ...
	//return Response(403, nil),nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("EditEffect method not implemented")
}

// GetEffect - Get effect
func (s *EffectsApiService) GetEffect(ctx context.Context, effectName string) (ImplResponse, error) {
	// TODO - update GetEffect with the required logic for this service method.
	// Add api_effects_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, GetEffectResponse{}) or use other options such as http.Ok ...
	//return Response(200, GetEffectResponse{}), nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetEffect method not implemented")
}

// GetEffectList - Get effect list
func (s *EffectsApiService) GetEffectList(ctx context.Context, localization string, page int32, keywords string) (ImplResponse, error) {
	// TODO - update GetEffectList with the required logic for this service method.
	// Add api_effects_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, GetEffectListResponse{}) or use other options such as http.Ok ...
	//return Response(200, GetEffectListResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetEffectList method not implemented")
}
