/*
 * SweetPotato Server API
 *
 * Sonolusの基本APIを拡張する感じ。 ユーザー認証はFirebaseAuthorizationを通してやる。
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package potato

import (
	"context"
	"errors"
	"log"
	"net/http"

	"cloud.google.com/go/firestore"
)

// TestsApiService is a service that implents the logic for the TestsApiServicer
// This service should implement the business logic for every endpoint for the TestsApi API.
// Include any external packages or services that will be required by this service.
type TestsApiService struct {
	firestore *firestore.Client
	cache     *CacheService
}

// NewTestsApiService creates a default api service
func NewTestsApiService(firestore *firestore.Client, cache *CacheService) TestsApiServicer {
	return &TestsApiService{firestore: firestore, cache: cache}
}

// GetTestServerInfo - Get user server info
func (s *TestsApiService) GetTestServerInfo(ctx context.Context, testId string) (ImplResponse, error) {
	if _, err := s.cache.GetUserIdFromTest(testId); err != nil {
		return Response(http.StatusNotFound, nil), nil
	}
	welcome, err := s.cache.news.Get("sweetPotatoTestWelcome")
	parsedNews := welcome.(News)
	if err != nil {
		log.Print(err)
		return Response(http.StatusInternalServerError, nil), nil
	}
	parsedNews.Level.Artists = testId
	welcome2, err := s.cache.news.Get("sweetPotatoTestWelcome2")
	parsedNews2 := welcome2.(News)
	if err != nil {
		log.Print(err)
		return Response(http.StatusInternalServerError, nil), nil
	}
	resp := ServerInfo{
		Levels:      []Level{parsedNews.Level, parsedNews2.Level},
		Skins:       []Skin{},
		Backgrounds: []Background{},
		Effects:     []Effect{},
		Particles:   []Particle{},
		Engines:     []Engine{},
	}
	return Response(200, resp), nil
}

// GetTestsBackgrounds - Get backgrounds for test
func (s *TestsApiService) GetTestsBackgrounds(ctx context.Context, testId string, localization string, page int32, keywords string) (ImplResponse, error) {
	// TODO - update GetTestsBackgrounds with the required logic for this service method.
	// Add api_tests_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, GetBackgroundListResponse{}) or use other options such as http.Ok ...
	//return Response(200, GetBackgroundListResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetTestsBackgrounds method not implemented")
}

// GetTestsEffects - Get effects for test
func (s *TestsApiService) GetTestsEffects(ctx context.Context, testId string, localization string, page int32, keywords string) (ImplResponse, error) {
	// TODO - update GetTestsEffects with the required logic for this service method.
	// Add api_tests_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, GetEffectListResponse{}) or use other options such as http.Ok ...
	//return Response(200, GetEffectListResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetTestsEffects method not implemented")
}

// GetTestsEngines - Get engines for test
func (s *TestsApiService) GetTestsEngines(ctx context.Context, testId string, localization string, page int32, keywords string) (ImplResponse, error) {
	// TODO - update GetTestsEngines with the required logic for this service method.
	// Add api_tests_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, GetEngineListResponse{}) or use other options such as http.Ok ...
	//return Response(200, GetEngineListResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetTestsEngines method not implemented")
}

// GetTestsLevels - Get levels for test
func (s *TestsApiService) GetTestsLevels(ctx context.Context, testId string, localization string, page int32, keywords string) (ImplResponse, error) {
	// TODO - update GetTestsLevels with the required logic for this service method.
	// Add api_tests_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, GetLevelListResponse{}) or use other options such as http.Ok ...
	//return Response(200, GetLevelListResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetTestsLevels method not implemented")
}

// GetTestsParticles - Get particles for test
func (s *TestsApiService) GetTestsParticles(ctx context.Context, testId string, localization string, page int32, keywords string) (ImplResponse, error) {
	// TODO - update GetTestsParticles with the required logic for this service method.
	// Add api_tests_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, GetParticleListResponse{}) or use other options such as http.Ok ...
	//return Response(200, GetParticleListResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetTestsParticles method not implemented")
}

// GetTestsSkins - Get skins for test
func (s *TestsApiService) GetTestsSkins(ctx context.Context, testId string, localization string, page int32, keywords string) (ImplResponse, error) {
	// TODO - update GetTestsSkins with the required logic for this service method.
	// Add api_tests_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, GetSkinListResponse{}) or use other options such as http.Ok ...
	//return Response(200, GetSkinListResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetTestsSkins method not implemented")
}
