/*
 * SweetPotato Server API
 *
 * Sonolusの基本APIを拡張する感じ。 ユーザー認証はFirebaseAuthorizationを通してやる。
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package potato

// GetLevelResponse - Response struct of getLevel
type GetLevelResponse struct {
	Item Level `json:"item"`

	Description string `json:"description"`

	Recommended []Level `json:"recommended"`
}
