/*
 * SweetPotato Server API
 *
 * Sonolusの基本APIを拡張する感じ。 ユーザー認証はFirebaseAuthorizationを通してやる。
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package potato

// User - ユーザー情報型
type User struct {

	// FirebaseDatabase上のユーザーID
	UserID string `json:"userId,omitempty" validate:"omitempty,alphanum,min=1,max=50"`

	// テスト用サーバーのエンドポイント
	TestID string `json:"testId,omitempty" validate:"alphanum,min=1,max=50"`

	// 管理者か否か
	IsAdmin bool `json:"isAdmin,omitempty"`

	// アカウント削除フラグ(trueで削除済み扱い)
	IsDeleted bool `json:"isDeleted,omitempty"`

	// トータル譜面数
	TotalFumen int32 `json:"totalFumen,omitempty" validate:"gte=0"`

	// 独自要素: データを作成したエポックミリ秒(ソート用)
	CreatedTime int32 `json:"createdTime,omitempty" validate:"gte=1"`

	// 独自要素: データを更新したエポックミリ秒(ソート用)
	UpdatedTime int32 `json:"updatedTime,omitempty" validate:"gte=1"`

	// 独自要素: サイト内および譜面情報欄に表示される説明文
	Description string `json:"description,omitempty" validate:"min=1,max=3000"`
}
