/*
 * SweetPotato Server API
 *
 * Sonolusの基本APIを拡張する感じ。 ユーザー認証はFirebaseAuthorizationを通してやる。
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package potato

// Background - A background provides background graphical element to levels / It defines background used for specific level https://github.com/NonSpicyBurrito/sonolus-wiki/wiki/Background
type Background struct {

	// english and number only name for searching
	Name string `json:"name"`

	// Reserved for future update. current default is 1.
	Version int32 `json:"version"`

	// base title of this content
	Title string `json:"title"`

	// something footer(ex. featuring xyz) for this content
	Subtitle string `json:"subtitle"`

	// author of this content
	Author string `json:"author"`

	Thumbnail SonolusResourceLocator `json:"thumbnail"`

	Data SonolusResourceLocator `json:"data"`

	Image SonolusResourceLocator `json:"image"`

	// 独自要素: データを作成したエポックミリ秒(ソート用)
	CreatedTime int32 `json:"createdTime,omitempty"`

	// 独自要素: データを更新したエポックミリ秒(ソート用)
	UpdatedTime int32 `json:"updatedTime,omitempty"`
}
