/*
 * SweetPotato Server API
 *
 * Sonolusの基本APIを拡張する感じ。 ユーザー認証はFirebaseAuthorizationを通してやる。
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package potato

// GetSkinResponse - Response struct of getSkin
type GetSkinResponse struct {
	Item Skin `json:"item"`

	Description string `json:"description"`

	Recommended []Skin `json:"recommended"`
}
