/*
 * SweetPotato Server API
 *
 * Sonolusの基本APIを拡張する感じ。 ユーザー認証はFirebaseAuthorizationを通してやる。
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package potato

// User - ユーザー情報型
type User struct {

	// FirebaseDatabase上のユーザーID
	UserId string `json:"userId,omitempty"`

	// テスト用サーバーのエンドポイント
	TestId string `json:"testId,omitempty"`

	// 管理者か否か
	IsAdmin bool `json:"isAdmin,omitempty"`

	// アカウント削除フラグ(trueで削除済み扱い)
	IsDeleted bool `json:"isDeleted,omitempty"`

	// トータル譜面数
	TotalFumen int32 `json:"totalFumen,omitempty"`

	// 独自要素: データを作成したエポックミリ秒(ソート用)
	CreatedTime int32 `json:"createdTime,omitempty"`

	// 独自要素: データを更新したエポックミリ秒(ソート用)
	UpdatedTime int32 `json:"updatedTime,omitempty"`
}
