/*
 * SweetPotato Server API
 *
 * Sonolusの基本APIを拡張する感じ。 ユーザー認証はFirebaseAuthorizationを通してやる。
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package potato

// GetEngineResponse - Response struct of getEngine
type GetEngineResponse struct {
	Item Engine `json:"item"`

	Description string `json:"description"`

	Recommended []Engine `json:"recommended"`
}
