/*
 * SweetPotato Server API
 *
 * Sonolusの基本APIを拡張する感じ。 ユーザー認証はFirebaseAuthorizationを通してやる。
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package potato

// GetUserListResponse - Structure of getList response
type GetUserListResponse struct {

	// サーバーに登録されたユーザー一覧
	Users []User `json:"users"`

	// 合計アカウント数
	Total int32 `json:"total"`

	// 合計ページ数
	Pages int32 `json:"pages"`
}
