/*
 * SweetPotato Server API
 *
 * Sonolusの基本APIを拡張する感じ。 ユーザー認証はFirebaseAuthorizationを通してやる。
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package potato

// LevelUseParticle  - struct to define what particle does the level uses.
// Item can be empty if UseDefault is true.
type LevelUseParticle struct {

	// If true (recommended), default resource specified by the engine will be used.
	UseDefault bool `json:"useDefault"`

	Item *Particle `json:"item,omitempty" validate:"omitempty"`
}
